### PR TITLE
refactor: move service packages into the `server/service/` directory

### PR DESCRIPTION
**Pull request by youngjoon-lee**
To make the product structure clearer, I just moved all service packages (such as `/server/datapool`) into the `server/service/`.
It's reasonable because all service packages embed the `Service` struct defined in the `server/service/service.go`.

[I've also considered merged the following two packages](https://github.com/medibloc/panacea-data-market-validator/pull/57#discussion_r833906778), but I'm not sure yet which way is the best. So, I didn't make any change about it in this PR.
```
"github.com/medibloc/panacea-data-market-validator/server/tee"
"github.com/medibloc/panacea-data-market-validator/tee"
```

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Review by hansol-medi — APPROVED** [review]
LGTM 👍

**Review by inchori — APPROVED** [review]
LGTM 👍

**Review by inchori — APPROVED** [review]
LGTM

**Pull request merged**
