### PR TITLE
feat: added a datapool e2e-test

### PR DESCRIPTION
**Pull request by gyuguen**

### CODE REVIEW

**Comment by gyuguen** [comment]
The e2e-test failure will be resolved when these [PR](https://github.com/medibloc/panacea-core/pull/297) are merged.

**Review by youngjoon-lee — APPROVED** [review]
LGTM

**Comment by hansol-medi** [comment]
The `deposit` field has been removed ([moved to genesis param](https://github.com/medibloc/panacea-core/pull/294)).
So you may have to remove that field for e2e test as well. Thank you!

**Comment by gyuguen** [comment]
> The `deposit` field in `PoolParams` has been removed ([moved to genesis param](https://github.com/medibloc/panacea-core/pull/294)). So you may have to remove that field for e2e test as well. Thank you!

OK, I got it. Thank you

**Pull request merged**
